[tool.pytest.ini_options]
addopts = "-q --strict-markers"
testpaths = ["tests"]
pythonpath = ["."]

[tool.coverage.run]
source = ["backtester"]
branch = false

[tool.coverage.report]
fail_under = 90
show_missing = true
